version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017 Preview
init:
- ps: dotnet --info
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- ps: dotnet restore
build_script:
- ps: dotnet build
test_script:
- ps: dotnet test PushMate.TemplatingService.Test --no-build